- name: install maven
  ansible.builtin.package:
    name: maven
    state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: "mv target/{{component}}-1.0.jar {{component}}.jar"
  args:
    chdir: /app

